// src/lib/geminiExe.ts

import {
    GoogleGenerativeAI,
    GenerationConfig,
    SafetySetting,
    HarmCategory,
    HarmBlockThreshold,
} from '@google/generative-ai';


// --- Appwrite Type Imports ---
import { UserProfile } from './appwrite'; // Adjust path if necessary

// --- Import the central Gemini service ---
import geminiService, { AppChatMessage } from './gemini';

// --- Constants for Type Validation (Unchanged) ---

/** Valid exercise intensity levels. */
export const VALID_EXERCISE_INTENSITIES = ["Gentle", "Light", "Moderate"] as const;
/** Union type representing allowed exercise intensities. */
export type ExerciseIntensity = typeof VALID_EXERCISE_INTENSITIES[number];

// --- Interface Definitions (Unchanged) ---

/**
 * Represents a single exercise suggestion generated by the AI.
 */
export interface ExerciseSuggestion {
  id: string;
  name: string;
  description: string;
  intensity: ExerciseIntensity | string;
  durationReps?: string;
  focusArea?: string;
  safetyNotes: string;
  reasoning?: string;
}

/** Structure for the AI's response, specialized for exercises */
export interface PersonalizedExerciseContent {
  exercises: ExerciseSuggestion[];
}

/** Options to customize the exercise generation request */
export interface ExerciseGenerationOptions {
  count?: number;
  customPreference?: string;
}

// --- Configuration ---
// The API key and model initialization are now handled centrally in `gemini.ts`

// --- Helper Functions (Unchanged Logic) ---

/**
 * Helper to get basic trimester info based on weeks pregnant.
 */
const getTrimesterInfo = (weeks: number | string | undefined | null): string => {
    const numWeeks = parseInt(String(weeks), 10);
    if (isNaN(numWeeks) || numWeeks < 1) return "Pregnancy stage unknown";
    if (numWeeks <= 13) return "First trimester";
    if (numWeeks <= 27) return "Second trimester";
    if (numWeeks <= 42) return "Third trimester";
    return "Post-term or invalid weeks";
};

/**
 * Creates the detailed prompt for the AI based on user profile and options,
 * focused solely on generating exercise suggestions. The logic is AI-provider agnostic.
 */
const createExercisePersonalizationPrompt = (profile: UserProfile, options: ExerciseGenerationOptions = {}): string => {
    const { count = 3, customPreference } = options;
    const weeks = profile.weeksPregnant ?? 'unknown';
    const activity = profile.activityLevel ?? 'unspecified';
    const conditions = profile.preExistingConditions?.trim() || 'none specified';

    let context = `**User Context:**\n`;
    context += `- Pregnancy Stage: ${weeks} weeks (Implications: ${getTrimesterInfo(weeks)})\n`;
    context += `- Stated Activity Level: ${activity}\n`;
    if (conditions !== 'none specified') {
        context += `- Stated Pre-existing Conditions: ${conditions} (Acknowledge for context only, DO NOT give medical advice related to these, but consider for exercise safety e.g., suggest lower impact if joint pain mentioned)\n`;
    }
    if (customPreference?.trim()) {
        context += `- User's Current Exercise Request/Focus: "${customPreference.trim()}"\n`;
    }
    if (weeks === 'unknown' && activity === 'unspecified' && conditions === 'none specified') {
        context += `- Note: User profile context is minimal. Provide generally safe and helpful pregnancy exercise suggestions (Gentle/Light intensity).\n`;
    }

    const safetyInstructions = `
**Safety & Role Definition:**
- You are MamaSaheli, an informational assistant providing general exercise suggestions. You are **NOT** a medical professional. Your advice is not a substitute for professional consultation.
- **ALL exercise suggestions are purely informational and MUST NOT be taken as medical or professional advice.**
- **CRITICAL (Exercise Safety):** For **every** exercise suggestion, the "safetyNotes" field **MUST** clearly state: "Consult your doctor before starting any new exercise during pregnancy. Listen to your body and stop immediately if you feel pain, dizziness, shortness of breath, or discomfort." Add any specific precautions relevant to the exercise itself.
- Base suggestions on general, evidence-based knowledge about safe exercise during pregnancy.
- Ensure suggested intensity aligns with: ${VALID_EXERCISE_INTENSITIES.join(', ')}.
- **DO NOT** suggest exercises that are generally contraindicated in pregnancy.
- **DO NOT** attempt to diagnose, treat, or manage any medical conditions mentioned.
`;

    const outputFormatInstructions = `
**Output Format Instructions:**
Provide the response STRICTLY as a valid JSON object. NO extra text, greetings, or explanations outside the JSON structure.
The top-level JSON object MUST ONLY have a single key: "exercises". The value of "exercises" MUST be an array of Exercise Suggestion objects.

Generate approximately ${count} valid exercise suggestions.

**Exercise Suggestion Object Structure (within "exercises" array):**
- "id": (string) A unique identifier (e.g., "ex-1").
- "name": (string) Clear name of the exercise.
- "description": (string) 1-3 sentences explaining how to perform it or its benefits. Use Markdown.
- "intensity": (string) Must be one of: ${VALID_EXERCISE_INTENSITIES.join(', ')}.
- "durationReps": (string, optional) e.g., "15-20 minutes".
- "focusArea": (string, optional) e.g., "Pelvic Floor".
- "safetyNotes": (string) **MANDATORY.** Must include the general consultation reminder AND specific precautions.
- "reasoning": (string, optional) Max 20 words on why this suggestion is relevant.

**Example Exercise Object:**
{
  "id": "ex-1",
  "name": "Pelvic Tilts (Cat-Cow Stretch)",
  "description": "Start on your hands and knees. As you inhale, drop your belly towards the floor (Cow). As you exhale, round your spine towards the ceiling (Cat). Helps relieve back discomfort.",
  "intensity": "Gentle",
  "durationReps": "Repeat 10-15 times",
  "focusArea": "Back Pain Relief, Pelvic Mobility",
  "safetyNotes": "Consult your doctor before starting any new exercise during pregnancy. Listen to your body and stop immediately if you feel pain, dizziness, or discomfort. Move gently and avoid over-arching your back.",
  "reasoning": "Gentle movement to ease back tension common in pregnancy."
}

**CRITICAL Rules:**
- **Output ONLY the JSON object string.** No introductory text or markdown formatting outside the JSON string values.
- Adhere STRICTLY to the requested JSON structure.
- Ensure valid JSON syntax: double quotes for all keys and string values.
- Ensure all mandatory fields are present and non-empty.
`;

    return `
You are MamaSaheli, an informational assistant. Provide safe, general exercise suggestions based on the user's profile, adhering strictly to safety guidelines and the required JSON output format.

${context}
${safetyInstructions}
Generate personalized, pregnancy-safe exercise suggestions based *specifically* on the user's context. Adhere precisely to the output format instructions below.
${outputFormatInstructions}
`;
};


/**
 * Parses and validates the AI's JSON response for exercise suggestions.
 * Cleans the string before parsing and filters out invalid items.
 */
const parseAndValidateExerciseContent = (responseText: string): PersonalizedExerciseContent => {
    // Clean the response to extract only the JSON object
    let cleanedJsonString = responseText.trim();
    const jsonStartIndex = cleanedJsonString.indexOf('{');
    const jsonEndIndex = cleanedJsonString.lastIndexOf('}');

    if (jsonStartIndex === -1 || jsonEndIndex === -1 || jsonEndIndex < jsonStartIndex) {
        throw new Error("AI response did not contain a recognizable JSON object.");
    }
    cleanedJsonString = cleanedJsonString.substring(jsonStartIndex, jsonEndIndex + 1);

    let parsedData: unknown;
    try {
        parsedData = JSON.parse(cleanedJsonString);
    } catch (parseError: unknown) {
        throw new Error(`Failed to parse AI suggestions. Invalid JSON format. ${parseError instanceof Error ? `Details: ${parseError.message}` : ''}`);
    }

    if (typeof parsedData !== 'object' || parsedData === null) {
        throw new Error("Validation Error: AI response is not a JSON object.");
    }

    const potentialContent = parsedData as Record<string, unknown>;
    const validatedOutput: PersonalizedExerciseContent = { exercises: [] };

    if (!Object.prototype.hasOwnProperty.call(potentialContent, 'exercises') || !Array.isArray(potentialContent.exercises)) {
        throw new Error("Validation Error: AI response missing required 'exercises' array.");
    }

    validatedOutput.exercises = potentialContent.exercises
        .map((item: unknown): ExerciseSuggestion | null => {
            if (typeof item !== 'object' || item === null) return null;
            const ex = item as Record<string, unknown>;

            if (typeof ex.id !== 'string' || !ex.id.trim() ||
                typeof ex.name !== 'string' || !ex.name.trim() ||
                typeof ex.description !== 'string' || !ex.description.trim() ||
                typeof ex.intensity !== 'string' || !ex.intensity.trim() ||
                typeof ex.safetyNotes !== 'string' || !ex.safetyNotes.trim()) {
                return null;
            }

            const durationReps = (typeof ex.durationReps === 'string' && ex.durationReps.trim()) ? ex.durationReps.trim() : undefined;
            const focusArea = (typeof ex.focusArea === 'string' && ex.focusArea.trim()) ? ex.focusArea.trim() : undefined;
            const reasoning = (typeof ex.reasoning === 'string' && ex.reasoning.trim()) ? ex.reasoning.trim() : undefined;
            const finalIntensity = VALID_EXERCISE_INTENSITIES.includes(ex.intensity as ExerciseIntensity) ? ex.intensity : "Gentle";

            return {
                id: ex.id.trim(),
                name: ex.name.trim(),
                description: ex.description.trim(),
                intensity: finalIntensity,
                durationReps,
                focusArea,
                safetyNotes: ex.safetyNotes.trim(),
                reasoning,
            };
        })
        .filter((item): item is ExerciseSuggestion => item !== null);

    if (validatedOutput.exercises.length === 0 && potentialContent.exercises.length > 0) {
       console.warn("Validation Warning: AI 'exercises' array contained items, but none passed validation.");
    }

    return validatedOutput;
};


// --- Public API Function (Updated for Gemini) ---

/**
 * Fetches personalized exercise suggestions from the Gemini API.
 */
export const generateExerciseSuggestions = async (
    profile: UserProfile,
    options: ExerciseGenerationOptions = {}
): Promise<PersonalizedExerciseContent> => {
    if (!geminiService) {
        throw new Error("Exercise suggestion service unavailable (Gemini client not initialized). Check API Key.");
    }

    const prompt = createExercisePersonalizationPrompt(profile, options);
    // For Gemini, we use a system prompt and a simple user prompt to trigger it.
    const messages: AppChatMessage[] = [
        { role: 'system', content: prompt },
        { role: 'user', content: 'Please generate the exercise suggestions now.' }
    ];

    try {
        // Call the central geminiService to handle the API request
        const responseText = await geminiService.sendMessage(messages);

        if (responseText === null || responseText === undefined || responseText.trim() === '') {
             console.warn("Gemini returned an empty response. Returning empty suggestions.");
             return { exercises: [] };
        }

        return parseAndValidateExerciseContent(responseText);

    } catch (error: unknown) {
        console.error(`Error during Gemini exercise personalization fetch/parse:`, error);
        if (error instanceof Error) {
            // Re-throw specific errors to be caught by the UI
            throw new Error(`Exercise personalization service API error: ${error.message}`);
        } else {
            throw new Error("An unexpected error occurred while fetching personalized exercise content.");
        }
    }
};

// --- Service Object Export (Renamed) ---
export const geminiExeService = {
    generateExerciseSuggestions,
};

// --- Type alias for frontend compatibility (Unchanged) ---
export type GenerationOptions = ExerciseGenerationOptions;